"""add qr column

Revision ID: 506ffd586697
Revises: a92ac5421fd0
Create Date: 2023-04-22 12:45:35.450566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506ffd586697'
down_revision = 'a92ac5421fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.drop_column('qr')

    # ### end Alembic commands ###
