"""add date column to attendance

Revision ID: a92ac5421fd0
Revises: edc39d0c5c1f
Create Date: 2023-04-21 15:47:50.341393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a92ac5421fd0'
down_revision = 'edc39d0c5c1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
