"""add password to student and prof

Revision ID: b1c38c46096e
Revises: 2557e214303f
Create Date: 2022-12-30 16:20:59.559856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c38c46096e'
down_revision = '2557e214303f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=100), nullable=True))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('password')

    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
